# Generated by Django 5.2.8 on 2025-11-12 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(3, 'Название должно быть от 3 до 300 символов')], verbose_name='Название места')),
                ('description_short', models.TextField(max_length=1000, verbose_name='Краткое описание')),
                ('description_long', models.TextField(max_length=5000, verbose_name='Полное описание')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('imgs', models.ImageField(upload_to='', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
