# Generated by Django 5.2.8 on 2025-11-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='imgs',
            field=models.ImageField(upload_to=['img/'], verbose_name='Изображения'),
        ),
    ]
