# Generated by Django 5.2.8 on 2025-11-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='imgs',
            field=models.ImageField(upload_to=['.'], verbose_name='Изображения'),
        ),
    ]
