# Generated by Django 5.2.8 on 2025-11-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_place_imgs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Позиция'),
            preserve_default=False,
        ),
    ]
