# Generated by Django 5.2.8 on 2025-11-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_image_position'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('place', 'position'), name='unique_position_per_place'),
        ),
    ]
