# Generated by Django 5.2.8 on 2025-12-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['position'], name='places_imag_positio_b2104b_idx'),
        ),
    ]
